name: "* Publish Production Veni"

on:
  push:
    branches:
      - main

jobs:
  publish_production_veni:
    name: Publish Production Domain Services
    uses: ./.github/workflows/publish-veni.yml
    with:
      branch: main
      tag: latest
    secrets: inherit