name: Publish Veni

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to publish from
        required: true
        type: string
        default: main
      tag:
        description: Tag to publish with
        required: true
        type: string
        default: latest
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        default: main
      tag:
        required: true
        type: string
        default: latest
    secrets:
      docker_username:
        required: true
      docker_access_token:
        required: true
      discord_builds_webhook:
        required: true

jobs:
  publish_for_platforms:
    strategy:
      matrix:
        include:
          - name: amd64
            runner: ubuntu-24.04
            alias: linux/amd64
            tag: amd64
          - name: arm64
            runner: ubuntu-24.04-arm
            alias: linux/arm64
            tag: arm64

    name: Publish Veni for ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build and push API Gateway docker image
        run: |
          docker build --push --platform ${{ matrix.alias }} \
          -t ${{ secrets.DOCKER_USERNAME }}/ffxivvenues.veni:${{ inputs.tag }}-${{ matrix.tag }} ./


  publish_multiplatform_manifest:
    name: Publish Veni multiplatform manifest
    runs-on: ubuntu-latest
    needs: publish_for_platforms

    steps:
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Create and push manifest
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/ffxivvenues.veni:${{ inputs.tag }} \
            ${{ secrets.DOCKER_USERNAME }}/ffxivvenues.veni:${{ inputs.tag }}-amd64 \
            ${{ secrets.DOCKER_USERNAME }}/ffxivvenues.veni:${{ inputs.tag }}-arm64
          
  notify_discord:
    name: Notify Discord webhook
    runs-on: ubuntu-latest
    needs: publish_multiplatform_manifest
    steps:
      
      - name: Notify Discord webhook
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
          embed-author-name: "${{ github.workflow }}"
          embed-title: "${{ github.event.head_commit.message }}"
          embed-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "${{ github.event }} by ${{ github.actor }}"
          embed-color: ${{ job.status == 'success' && '3066993' || '15158332' }}
